### ISSUE TITLE
Game Crash when trying to open PlayerEx Menu.

### ISSUE THREAD

**Issue by QuentinMoriceau-HRC** [CleverNucleus/PlayerEx#28]
Hello,
Thank you for this mod, it looks really good but unfortunately, I can't enjoy its features. When I try to open the menu (by clicking on the button in our inventory), the game crashes, I tried with only this mod and I still have the problem.

I attach the crash logs.

Thanks in advance :D
`---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 20/09/2021 14:12
Description: Rendering screen

java.lang.NoSuchMethodError: 'float com.github.clevernucleus.dataattributes.api.attribute.IAttribute.getProperty(java.lang.String)'
	at com.github.clevernucleus.playerex.api.client.ClientUtil.displayValue(ClientUtil.java:44)
	at com.github.clevernucleus.playerex.client.gui.AttributesPageLayer.lambda$static$30(AttributesPageLayer.java:229)
	at com.github.clevernucleus.playerex.api.client.RenderComponent.renderText(RenderComponent.java:55)
	at com.github.clevernucleus.playerex.client.gui.AttributesPageLayer.lambda$render$55(AttributesPageLayer.java:450)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.clevernucleus.playerex.client.gui.AttributesPageLayer.method_25394(AttributesPageLayer.java:450)
	at com.github.clevernucleus.playerex.client.gui.AttributesScreen.lambda$render$6(AttributesScreen.java:79)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at com.github.clevernucleus.playerex.client.gui.AttributesScreen.method_25394(AttributesScreen.java:79)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.clevernucleus.playerex.api.client.ClientUtil.displayValue(ClientUtil.java:44)
	at com.github.clevernucleus.playerex.client.gui.AttributesPageLayer.lambda$static$30(AttributesPageLayer.java:229)
	at com.github.clevernucleus.playerex.api.client.RenderComponent.renderText(RenderComponent.java:55)
	at com.github.clevernucleus.playerex.client.gui.AttributesPageLayer.lambda$render$55(AttributesPageLayer.java:450)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.clevernucleus.playerex.client.gui.AttributesPageLayer.method_25394(AttributesPageLayer.java:450)
	at com.github.clevernucleus.playerex.client.gui.AttributesScreen.lambda$render$6(AttributesScreen.java:79)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at com.github.clevernucleus.playerex.client.gui.AttributesScreen.method_25394(AttributesScreen.java:79)

-- Screen render details --
Details:
	Screen name: com.github.clevernucleus.playerex.client.gui.AttributesScreen
	Mouse location: Scaled: (291, 49). Absolute: (583.000000, 98.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['momokinou'/167, l='ClientLevel', x=-319.59, y=13.00, z=130.13]]
	Chunk stats: 4761, 707
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,87,16), Section: (at 0,7,0 in -16,5,1; chunk contains blocks -256,-64,16 to -241,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 86956 game time, 103822 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Programmer Art`

**Comment by CleverNucleus** [comment]
Read the text written in **bold** at the very top of the [page](https://www.curseforge.com/minecraft/mc-mods/playerex).

See [this](https://www.curseforge.com/minecraft/mc-mods/playerex?comment=444) comment thread.

**Comment by QuentinMoriceau-HRC** [comment]
Thank, sorry for not being able to read properly ...
I'll wait the next version :D
