### ISSUE TITLE
Library conflict

### ISSUE THREAD

**Issue by Eric-liucn** [CleverNucleus/PlayerEx#67]
when using playerEx commands
```
java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Sets
	at com.github.clevernucleus.playerex.impl.CommandsImpl.lambda$static$0(CommandsImpl.java:35)
	at com.github.clevernucleus.playerex.impl.CommandsImpl.lambda$static$1(CommandsImpl.java:36)
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71)
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:598)
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:580)
	at net.minecraft.class_3244.method_12059(class_3244.java:481)
	at net.minecraft.class_2805.method_12147(class_2805.java:29)
	at net.minecraft.class_2805.method_11054(class_2805.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Sets
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 22 more
```

full [log and crash report](https://gist.github.com/Eric-liucn/dd88d865c213bd368ac0296140f844cc)

**Comment by Eric-liucn** [comment]
version playerex-3.2.0.jar

**Comment by CleverNucleus** [comment]
Hi there,
Thanks for the report; this is a bit of a weird one, it looks like the apache commons library is missing, but that itself would be odd as it's a dependency for vanilla Minecraft. I'll look into it.

**Comment by CleverNucleus** [comment]
Fixed, pending actual release upload on Curseforge.
